### ISSUE TITLE
ng test <project> --find-related-tests  doesn't seem to work

### ISSUE THREAD

**Issue by pierceo** [just-jeb/angular-builders#1023]
**Is your feature request related to a problem? Please describe.**
 
On git commits I'd like to be able to run only _related_ tests, using husky and lint-staged.  

The problem is, when I run:

`ng test <project> --find-related-tests ./src/source.js`

I can see the path is treated as an option, and I get the error  

`Unknown option: './src/source.js'`

For comparison, the following works fine, so I know this option and its value are being passed to JEST: 

`ng test <project> --testNamePattern="component"` (runs all specs with 'component' in the name)

**Describe the solution you'd like**
I would like the path to be supported and passed to JEST

**Describe alternatives you've considered**
I'm considering using husky/lint-staged to run a different batch of tests based on the changed files.

**Comment by just-jeb** [comment]
Hi, please try `--findRelatedTests`.

**Comment by pierceo** [comment]
Hi, Thanks for the reply. 
I'm still getting the same error though
`ng test --findRelatedTests ./somefile.ts`

![image](https://user-images.githubusercontent.com/4246439/128718112-91c36403-0776-4e6f-aead-495c20228e5c.png)


Whereas this works fine 
`ng test --testNamePattern="util"`
![image](https://user-images.githubusercontent.com/4246439/128717933-864c3070-f5a6-4ee7-81cb-4bba4996d336.png)

**Comment by just-jeb** [comment]
OK, I'll look into it. Meanwhile could you try `--findRelatedTests="./somefile.ts"`?

**Comment by just-jeb** [comment]
Issue confirmed, the problem is wrong argument type (should be a list of strings, but is a boolean).  
I want to investigate it a bit more before providing a fix, since I took the schema right from [Jest CLI repo](https://github.com/facebook/jest/blob/master/packages/jest-cli/src/cli/args.ts#L272) and it is boolean there.

**Comment by just-jeb** [comment]
The way it works in Jest is actually described in the docs: 
>Find and run the tests that cover a space separated list of source files that were passed in as arguments.

So the option is indeed `boolean` but the list of source files is passed as arguments.  

Angular CLI is more strict and options passed to CLI should comply with the builder's schema (hence you can't just pass list of source files as arguments, they have to be passed as part of a certain option).

**Comment by just-jeb** [comment]
The fix is available in `@angular-builders/jest@12.1.1-beta.0`, please try it out and let me know if there are still issues. If all is good I'll graduate it to a stable release.

**Comment by just-jeb** [comment]
OK, I assume the tests I added are enough. Graduating to stable release.

**Comment by pierceo** [comment]
Sorry for the delay, I just checked.  It works fine now, thanks.  
It seems the schema has changed though, I had to update the options to solve these errors: 

![image](https://user-images.githubusercontent.com/4246439/129904392-75183bed-e81d-44ac-a908-777fa9d81497.png)

![image](https://user-images.githubusercontent.com/4246439/129904656-a22f7797-a20a-4b0c-a902-dae4e0bcddcf.png)

**Comment by MaxLat** [comment]
Hi pierceo, 

How can you solved this error "Data path polyfills must be array" ? 

Thanks :)

**Comment by pierceo** [comment]
I just changed angular.json 

`"polyfills": "apps/myapp/src/polyfills.ts", `
to
` "polyfills": "[apps/myapp/src/polyfills.ts]",`

**Comment by MaxLat** [comment]
thanks :D it works !

**Comment by just-jeb** [comment]
@pierceo @MaxLat notice that the [right thing](https://github.com/just-jeb/angular-builders/issues/1030#issuecomment-911703823) would be removing the `polyfills` entry at all. Otherwise what you actually do is passing to `jest` the `polyfills` file as a test file.

**Comment by mykhailo-kazakov** [comment]
@just-jeb Hello! I noticed in my project that currently, ng test with --findRelatedTests flag works fine for 1 passed path only:
ng test --findRelatedTests first-path-to-file

If I try passing several files (ng test --findRelatedTests first-path-to-file second-path-to-file), it considers second-path-to-file as a project name:
![image](https://user-images.githubusercontent.com/93653138/144104762-8257266d-7962-4c00-b55e-fd8eea318801.png)

At the same time, if I use the same with the jest command, it works as expected:
![image](https://user-images.githubusercontent.com/93653138/144104870-21af79ad-c800-4bda-9862-6ec82ac34684.png)

Is there anything I can do to fix it on my side, or is there something required to be fixed in your implementation?

**Comment by just-jeb** [comment]
@mykhailo-kazakov Hey, could you please open a separate issue with all the details and reproduction? Thank you!

**Comment by mykhailo-kazakov** [comment]
@just-jeb Sure, here it is: https://github.com/just-jeb/angular-builders/issues/1065
