### ISSUE TITLE
When updating to latest version of @angular-builders/jest tests fail

### ISSUE THREAD

**Issue by joniruokamo** [just-jeb/angular-builders#1030]
## Describe the Bug

After updating to the latest 12.1.1 version from 12.1.0 version. I get this error when running tests with ng test:

`Schema validation failed with the following errors:   Data path "/polyfills" must be array.`

## Expected Behavior

No error in the runner when running tests

## Environment

Libs
- @angular/core version: 12.2.3
- @angular-devkit/build-angular version: 12.2.3
- @angular-builders/jest version: 12.1.1

For Tooling issues:
- Node version: 14.15.1
- Platform:  Mac

**Comment by just-jeb** [comment]
It's because of the updated version of `angular-devkit`. The solution would be to fix the schema (turn it into an array).

**Comment by astik** [comment]
In addition to polyfills, inlineStyleLanguage needs to be changed into an array.

When looking at [build option schema](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/utils/build-options.ts), we can see that those 2 properties are supposed to be a string, not an array.

It seems upgrading to 12.1.1 is not a simple patch but a breaking change. in the meantime i'm staying on 12.1.0.

**Comment by just-jeb** [comment]
I'm curious, why do you need `polyfills` entry in your `test` target at all when using `@angular-builders/jest` builder?  
[Here](https://github.com/just-jeb/angular-builders/blob/master/packages/jest/src/schema.json) is the builder's schema, it doesn't contain a `polyfills` field. 
The reason you're getting this error is that all the additional (non-schema) fields are considered [an array of strings](https://github.com/just-jeb/angular-builders/blob/master/packages/jest/src/schema.json#L485) (so that you'd be able to pass filenames to `ng test` just like you pass them to `jest`).  

My guess is that `polyfills` is a leftover from Karma builder you can safely remove it. The only options needed in `angular.json` are those mentioned [here](https://github.com/just-jeb/angular-builders/tree/master/packages/jest#builder-options).

**Comment by astik** [comment]
You are absolutely right!
Removing unneeded / unknown configuration from the test builder fixed everything!
Thank you =)

**Comment by joniruokamo** [comment]
Indeed there was a unnecessary `polyfills`. Removing it from options fixed the issue!
