### ISSUE TITLE
TypeError when trying to add a CustomTransformer for TypeScript

### ISSUE THREAD

**Issue by Nyphet** [just-jeb/angular-builders#1038]
## Describe the Bug

When I try to add a CustomTransformer, specifically [ts-transformer-keys](https://www.npmjs.com/package/ts-transformer-keys), to TypeScript via a rule in my extra webpack config file, it doesn't give any error in build but at runtime gives out this error in console:
![image](https://user-images.githubusercontent.com/65339023/133833129-332923f4-ecb0-4401-b5de-b907cd50bbf0.png)
which is also the same behavior I would get when importing the Transformer in my code while using the default Angular builder.

## Minimal Reproduction

My whole project where I'm trying to make this work is available [here](https://github.com/Nyphet/test-project).
In short I am trying to configure an Electron-Angular app with Webpack to make use of the CustomTransformer ts-transformer-keys.  
As it can be seen in the repository, the project is quite simple: it uses a basic Electron configuration (under src/electron) and an automatically generated Angular app (under src/renderer) with a slightly modified app.component to test the functionality I'm interested with.

## Expected Behavior

The CustomTransformer should correctly be used and I should not get an error message in console but instead the output of the imported function on my developer console.

## Environment

<pre><code>
Libs
- @angular/core version: 12.2.0
- @angular-devkit/build-angular version: 12.2.5
- @angular-builders/custom-webpack version: 12.1.2
- ts-transformer-keys: 0.4.3
- webpack: 5.52.1
- webpack-cli: 4.8.0

For Tooling issues:
- Node version: 14.17.1
- Platform:  Windows

Others:
</code></pre>

## Additional Context

When using the Custom Transformer within Electron built with Webpack, it works just fine.

**Comment by just-jeb** [comment]
Hey @Nyphet, [this](https://github.com/just-jeb/angular-builders/issues/484#issuecomment-529105020) is probably the solution for you.

**Comment by Nyphet** [comment]
Hi @just-jeb, I checked the solution proposed, but I think it's outdated since now [AngularCompilerPlugin](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts) gives a 404.
I still tried to make it work with the latest version of ngtools and I have updated the [repository](https://github.com/Nyphet/test-project) with my try, but in the end I get the same error.

**Comment by just-jeb** [comment]
Yup, you're right, that's because `AngularCompilerPlugin` has been replaced with [`AngularWebpackPlugin`](https://github.com/angular/angular-cli/blob/ccb5f3f6bbd22a083c8408c652058154a9a47125/packages/ngtools/webpack/src/ivy/plugin.ts#L100). Which doesn't seem to have an option to add custom transformers... I'll try to check with Angular team if there is still an option to do that.

**Comment by just-jeb** [comment]
So there is nothing even semi-official (like `platformTransformers`) that allows you to add a custom transformer.   
There is, however, an [ugly workaround](https://github.com/NativeScript/NativeScript/commit/c265c3ac3f7a9b770de86fd58cb7b2cb661570d0#diff-45f4e6ff45c508724bfdf20be521f824a2ccebbb80bc79d7d9f032221bb7d4ca) you can do by altering `AngularWebpackPlugin` prototype like described [here](https://github.com/angular/angular-cli/pull/21046#issuecomment-859777014).  
That said, I'd advise strongly against that, because it deeply relies on internal implementation and can break very quickly.   

Not an issue with the builder though, so I'm closing the issue.
