### ISSUE TITLE
@angular-builders/jest - cannot define a virtualConsole for jsdom

### ISSUE THREAD

**Issue by matheo** [just-jeb/angular-builders#1058]
## Describe the Bug

Tracking the issue it seems that `argv.push('--config', JSON.stringify(configuration))` is unable to preserve the `VirtualConsole` type of my `{ testEnvironmentOptions: { virtualConsole: new VirtualConsole() } }` so I get an exception:

![image](https://user-images.githubusercontent.com/260185/142142593-d400af47-a9b3-4191-8957-03c9e8ff1f07.png)

anything we can do to preserve the type or have a separated config.js for jsdom?

We're getting annoyed with this kind of error in our tests after upgrading to v12:
https://github.com/jeffbski/wait-on/issues/64

## Environment

<pre><code>
Libs
- @angular/core version: 12.2.13
- @angular-devkit/build-angular version: 12.2.13
- @angular-builders/jest version: 12.1.2

For Tooling issues:
- Node version:14.17.3
- Platform: Linux

**Comment by just-jeb** [comment]
That is indeed an issue, since config is being stringified and passed to Jest CLI... Not sure if there is an immediate solution for this, looks like some research required.  
I can suggest a workaround though - how about using [custom environment](https://archive.jestjs.io/docs/en/22.x/configuration#testenvironment-string) which would extend `jsdom` environment and pass your `VirtualConsole` as an option to the constructor?  
A path to a file is a string so it will work just fine and since the custom environment file won't get stirngified your console should work properly.   

Btw, how comes you only experience it after upgrade to v12? The stringification has been there from basically day one...

**Comment by just-jeb** [comment]
It can be defined globally, as soon as you create custom environment you can just pass its path as an option to Jest Builder config.

**Comment by matheo** [comment]
@just-jeb thank you very much, that worked!
I've cloned the [jest-environment-jsdom code](https://github.com/facebook/jest/blob/main/packages/jest-environment-jsdom/src/index.ts) and added `omitJSDOMErrors` to remove that message :D
```typescript
        virtualConsole: new VirtualConsole().sendTo(
          options?.console || console,
          { omitJSDOMErrors: true }, // hides "Error: connect ECONNREFUSED 127.0.0.1:80"
        ),
```

Thank you again!

**Comment by just-jeb** [comment]
Glad it helped! You don't jave to copy it btw, you can just import the JsdomEnvironment class from the package and extend it with your own class that passes custom console to `super`.

**Comment by matheo** [comment]
Yeah, perhaps the `constructor` is huge, not quite a modular class to extend lol
