### ISSUE TITLE
Add ability to build angular libraries using ng-packagr module

### ISSUE THREAD

**Issue by Emaxan** [just-jeb/angular-builders#1059]
It will be cool to add the ability to compile libraries using custom webpack settings using [ng-packagr](https://github.com/ng-packagr/ng-packagr) module for publishing it to npm. I searched all day and didn't find anything for that.

It can be smth like in [builder in angular-devkit](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular/src/builders/ng-packagr).

**Comment by just-jeb** [comment]
It's a wonderful idea, but the thing is that `ng-packagr` doesn't use Webpack.  
In fact, `ng-packagr` has a completely custom build chain. The chain is based on transforms and pipelines (read more [here](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/docs/transformation-pipeline.md)).
This architecture is extensible to some degree however it’s still limited. For example, it's [nearly impossible](https://github.com/ng-packagr/ng-packagr/issues/643) to modify css with this. If the `STYLESHEET_TRANSFORM` was implemented it would have been a easier but unfortunately it’s not implemented, despite being mentioned in one of the [examples](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/docs/transformation-pipeline.md#future-work-and-current-limitations).

You could have thought about trying to hook into `rollup` rather than `Webpack`, but `rollup` is used by `ng-packagr` solely for bundling purposes, it doesn’t take any part in compilation and file processing. 
`rollup` is applied inside `WRITE_BUNDLES` transform, which _is_ [implemented](https://github.com/ng-packagr/ng-packagr/blob/398b0854940af41be71a8d36d720bb71c71c50c0/src/lib/ng-package/entry-point/write-bundles.transform.ts), and it even [has an option](https://github.com/ng-packagr/ng-packagr/blob/e4e8d56c8b52bf610ed645ca7be9569a125ff2be/src/lib/flatten/rollup.ts#L25) for custom plugin. 
Since `WRITE_BUNDLES` is an existing transform, theoretically it could be replaced with a custom provider.   
However, `rollup` is applied deep inside this transform so you would have to basically copy-paste the entire transform tree down to the rollup function in order to be able to add your custom plugin. Which, obviously, can break with every minor release.  
But even when you did that it wouldn’t solve your problem entirely. `rollup` is processing only `fesm` and `umd` bundles and in library build you also have `esm` modules which are not processed by rollup.

Let’s face it - you cannot modify rollup process in order to change the final bundle.

Your another option is to try replacing the [`compileNgcTransform`](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/src/lib/ng-package/entry-point/compile-ngc.transform.ts) with a custom one which mimics its behavior but passes to [`compileSourceFiles`](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/src/lib/ng-package/entry-point/compile-ngc.transform.ts#L26) function a custom [`stylesheetProcessor`](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/src/lib/styles/stylesheet-processor.ts) (in case of CSS), which, in turn, is the same processor as the default but [applies](https://github.com/ng-packagr/ng-packagr/blob/baa67340e7781b29cf88cdbea9b7539765183f32/src/lib/styles/stylesheet-processor.ts#L113) additional postcss plugin.
This can be easily broken by a minor release too (since you copy-pasted the whole build pipeline) and it’s also hardly maintainable.
Moreover, if you managed to replace the whole pipeline and applied your post css plugin you still might have to modify the html. Which you can’t do inside the build process, because HTML and TS processing is done by [ng compiler host](https://github.com/ng-packagr/ng-packagr/blob/51d5498cb3ccc3974d57e12624676a122a04d982/src/lib/ngc/compile-source-files.ts#L44) and there is no way to hook into it. You’ll have to override the compiler host, and believe me, you don’t want it.

As you can see there is almost no way to modify the `ng-packagr` build.

In my opinion your best shot is to try modifying the final bundles/modules with a custom post-build script.

**Comment by Emaxan** [comment]
Thanks for such a detailed answer. It's a pity that it's impossible. Will try to find another way.
