### ISSUE TITLE
[@angular-builders/jest] Cannot get jest builder to work with jest-runner-eslint 

### ISSUE THREAD

**Issue by ryanknittel-fdx** [just-jeb/angular-builders#1063]
## Describe the Bug

I am trying to lint my spec.ts files on `ng lint` using [jest-runner-eslint](https://github.com/jest-community/jest-runner-eslint).

However, the lint project tests fail when I run `ng test`

I tried setting `preset: 'jest-preset-angular'` for the lint project. Also tried using `globalMocks` and `testEnvironment: 'jsdom'` with no success.

```

 FAIL  src/app/core/services/local-storage.service.spec.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/@angular-builders/jest/dist/global-mocks/computed-style.js:2:23)
          at Array.forEach (<anonymous>)
```

jest.config.js

```javascript
module.exports = {
	projects: [
		{
			displayName: 'lint',
			runner: 'jest-runner-eslint'
		},
		{
			preset: 'jest-preset-angular'
		}
	]
};
```

angular.json
```json
	"test": {
		"builder": "@angular-builders/jest:run",
		"options": {
			"polyfills": [
				"src/app/polyfills.ts"
			],
			"tsConfig": "tsconfig.spec.json",
			"watch": false
		}
	},
```
				

## Minimal Reproduction

https://github.com/ryanknittel-fdx/angular-builders-jest-eslint-issue

## Expected Behavior

jest-runner-eslint runs and lints files without ` ReferenceError: window is not defined` error

## Screenshots

![image](https://user-images.githubusercontent.com/93788678/143509480-cac01ad3-cea7-4e20-8804-cec414709cb1.png)

## Environment

<pre><code>
Libs
- @angular/core version: 12.2.13
- @angular-devkit/build-angular version: 12.2.13
- @angular-builders/jest version: 12.1.2

For Tooling issues:
- Node version: v16.13.0
- Platform:  Linux

Others:
VS Code
</code></pre>

**Comment by just-jeb** [comment]
Hey, thanks for raising this issue! 
The problem is that `jest-runner-eslint` are [loading the setup files](https://github.com/jest-community/jest-runner-eslint/blob/main/src/runner/runESLint.js#L74) that come from within Jest config while completely ignoring the configuration for Jest environment. Since they do it in a node process, `window` does not exist, hence the error.  
Notice that this will happen with any setup file (unrelated to `@angular-builders`) if it tries to access the window inside (in particular if it tries to setup some global mock). That's why I think the proper fix should come from `jest-runner-eslint`. 
Please create another issue on their repository if you want it to be fixed.   

What you can do meanwhile: 
1. If you don't need any global mocks that are [enabled by default](https://github.com/just-jeb/angular-builders/tree/master/packages/jest#builder-options) you can just disable them by passing an empty array to the configuration:
```json
"test": {
    "builder": "@angular-builders/jest:run",
    "options": {
        "globalMocks": [],
        "tsConfig": "tsconfig.spec.json",
        "watch": false
    }
},
```
Notice that it will disable global mocks for the tests as well (not just for linting).

2. Create two separate architect targets in `angular.json`, use one of them for linting and another for tests, while disabling the global mocks for linter target.
```json
"test": {
    "builder": "@angular-builders/jest:run",
    "options": {
        "tsConfig": "tsconfig.spec.json",
    }
},
"testLint": {
    "builder": "@angular-builders/jest:run",
    "options": {
        "globalMocks": [],
        "tsConfig": "tsconfig.spec.json",
        "configPath": "path-to-jest-config-with-eslint-runner"
    }
},
```

**Comment by ryanknittel-fdx** [comment]
Thanks for your help. I'll try these workarounds.
