### ISSUE TITLE
ng test --findRelatedTests file1 file2 does not work as expected

### ISSUE THREAD

**Issue by mykhailo-kazakov** [just-jeb/angular-builders#1065]
## Describe the Bug

Currently, ng test --findRelatedTests works correctly when passing 1 file only:
`ng test --findRelatedTests file1.ts`

When passing more than 1 files, the rest of the files are treated like CLI options:
`ng test --findRelatedTests file1 file2`
Here, file2 is considered project name (as in --project):
![image](https://user-images.githubusercontent.com/93653138/144129426-e1ba7413-f0db-4ecb-9563-709525c96a94.png)

## Expected Behavior

Both files should be taken into account when checking for related tests:
![image](https://user-images.githubusercontent.com/93653138/144129517-1cf078f2-4d0c-4091-a59b-4549edfd8dcf.png)

## Environment

"@angular-builders/custom-webpack": "^13.0",
"@angular-builders/jest": "^13.0",
"jest": "^27.4.2",
"@types/jest": "^27.0.3",

**Comment by just-jeb** [comment]
Can you please create a simple reproduction repo? Thank you!

**Comment by mykhailo-kazakov** [comment]
@just-jeb Here is the repo: https://github.com/mykhailo-kazakov/angular-jest-bug
To reproduce, please use: `npm run test:frt`

**Comment by mykhailo-kazakov** [comment]
@just-jeb Hi, is it enough for reproducing or can I help with anything else?

**Comment by just-jeb** [comment]
It's enough, thank you. Just haven't had time to tackle it yet.

**Comment by just-jeb** [comment]
Good news, this is indeed a bug in the builder schema and the fix is on its way.  
One thing that you should pay attention to is that Angular CLI receives array props with a comma delimiter and not a space delimiter.  
So after the fix comes out you'll have to use it this way: 
```sh
ng test --findRelatedTests file1,file2
```

Another thing is that I see that you're using Jest Builder 13 with Angular 11. The major versions of Angular and the builder must match, otherwise a lot of unexpected issues can arise. Although it should be less error prone with Jest builder (most of the issues would arise with Custom Webpack), I highly recommend you to upgrade your Angular version to the latest.

**Comment by just-jeb** [comment]
Should be fixed in `13.0.2-beta.0`. Could you confirm it please?

**Comment by mykhailo-kazakov** [comment]
Thank you, I confirm it is fixed after the upgrade.

**Comment by just-jeb** [comment]
Cool, so I'm graduating it to release.

**Comment by Babeetlebum** [comment]
Hello I was trying to use this feature to parallelize my tests on CircleCI but I'm struggling to make it work. In my case all tests are launched when using the `--find-related-tests` argument.

As an example I forked @mykhailo-kazakov 's repo and added a 3rd component for demonstration purposes as well as bumped the `@angular-builders/jest` version to `13.0.2` and changed the npm script syntax to use the comma separator as advised above.

This ends up running the 3 test suites (instead of only 2), can anybody reproduce this ?
![Screenshot from 2022-01-07 15-53-06](https://user-images.githubusercontent.com/5504984/148561767-2a4185d8-858e-435e-b236-f89d947a4012.png)

Don't hesitate to tell me if you'd like a separate issue for this

**Comment by just-jeb** [comment]
Mind the difference between `find-related-tests` and running specific tests.  
If you just want to run the two suits you passed in you shouldn't be passing any flags at all or, alternatively, use `testPathPattern` flag.

**Comment by Babeetlebum** [comment]
Thanks for your answer, it worked by separating them with a pipe `|`  
```
npm run test -- -- "src/app/app.component.spec.ts|src/app/child-component/child-component.component.spec.ts"
```
