### ISSUE TITLE
Breaking changes in angular.json makes "usage" instructions incomplete

### ISSUE THREAD

**Issue by sondreb** [just-jeb/angular-builders#1595]
Creating a new Angular (17) app using CLI, then performing the usage instructions for angular-builders, will result in an error like this:

```Data path "" must have required property 'main'.```

This doesn't explain what I did wrong, or what is additionally needed.

The default builder for Angular is now: `@angular-devkit/build-angular:application` ... is it planned to rename "browser" to "application" as well?

This default configuration has an attribute named `"browser": "src/main.ts",` while the angular-builders is looking for `"main": "src/main.ts",`

**Comment by just-jeb** [comment]
True, thanks for raising this. 
Regarding renaming, if it will happen then not before the next major release (since it is a breaking change). Also there is a new builder [being developed](https://github.com/just-jeb/angular-builders/pull/1536) for the `esbuild` extension, we'll need to see what makes sense. 

Meanwhile the instructions are indeed outdated, would you like to create a PR with updated instructions?

**Comment by Kitenite** [comment]
Coming here to bump this issue, I wasn't sure what was wrong with my custom weback setup so it took be a while to find this. Seems from the discussion here that I need to update browser to main which works.

This was very cryptic for me being newer to angular:
`Data path "" must have required property 'main'.`

**Comment by quinnjr** [comment]
I noticed in my installation of @angular/ssr that a number of properties are being marked as not being allowed.

**Comment by arturovt** [comment]
Closing since the new Angular application is created with the `:application` builder but the docs stated to replace the `:browser` builder with the custom Webpack. The ESBuild builder has been released (see `custom-esbuild`).
