### ISSUE TITLE
custom-webpack:browser build failed @angular18：Schema validation failed.....: Data path "" must have required property 'main'

### ISSUE THREAD

**Issue by hauxsoft** [just-jeb/angular-builders#1831]
## Describe the Bug

I created a new ng project by @angular/cli(v18.1.0)，and executed `npm i -D @angular-builders/custom-webpack` to install @angular-builders/custom-webpack 18.0.0。

Then I reset angular.json content, set project.[myAppName].architect.builder = "@angular-builders/custom-webpack:browser", accroding [custom-webpack README.md](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack)

After all, I runned cmd `ng build` to build project, but got the following error response in cmd terminal : 
`
Error: Schema validation failed with the following errors:
Data path "" must have required property 'main'. 
`

## Enviroment
"@angular-builders/custom-webpack":   "^18.0.0",
"@angular-devkit/build-angular":            "^18.1.0",
"@angular/cli":                                          "^18.1.0",
"node js":                                                   "22.0.0",

## Expected Behavior

repair the bug in angular18, thanks.

**Comment by just-jeb** [comment]
Most likely you have some issue with dependencies (also known as dependency hell). 
You can check it by `yarn why` command (or its NPM alternative).
Try to delete the lock file and node_modules and install the deps again. If that doesn't help then check that all the Angular libraries have a matching major version (in your case 18). 

Anyways, the examples in this repo run just fine, so it's very unlikely the issue is with the package itself.

**Comment by IsakEriksson** [comment]
Just out of curiosity, did you check that you have the correct browser/main property in build.options? I got the same error when I used build.options.browser and should have used build.options.main.

**Comment by manuelhumanescabrera** [comment]
In Angular v17.3.7 and custom-webpack v17.0.2 im facing the same problem, when i changed **browser** to **main** in the **angular.json** file i had now another error: `Data path "/serviceWorker" must be boolean.`. That looks like the schema validation is not the same used by angular-devkit on the same version.

**Comment by iamishver** [comment]
I am facing the same issue.....

**Comment by just-jeb** [comment]
Please provide a clean reproduction. Otherwise I won’t be able to help.

**Comment by iamishver** [comment]
Install the Angular 18.1.1 and try to set up the .env configuration. you will find the issue.

Older angular versions use "**main**" as a configuration to specify the entry point of your application.

In the latest angular version, it is changed as "**browser**" to specify the entry point of your application, 

![image](https://github.com/user-attachments/assets/506a832e-81ec-42a2-ba70-878f3fe8821d)

**Comment by just-jeb** [comment]
Please provide a link to a repository with a clean reproduction.

**Comment by isurendrasingh** [comment]
Angular team made some changes related to builder. The default will be `application` builder for newly generated applications (both v18@latest & v17@latest).

`New applications will use this new build system by default via the application builder.` [doc](https://angular.dev/tools/cli/build-system-migration#for-new-applications).

Since `@angular-builders/custom-webpack`  provides  `[browser|server|karma|dev-server|extract-i18n]`  builders and not `application` builder, the schema validation fails during serve or build step.

**Comment by arturovt** [comment]
Yes, you're mixing builders which are not compatible between each other. New Angular applications are using `application` builder which is using ESBuild while previous versions use Webpack by default.

**Comment by evert-vd** [comment]
same error Data path "" must have required property 'main' en angular@17.3.0 
![image](https://github.com/user-attachments/assets/40c36601-d807-46c4-a98d-97c85c94858b)

**Comment by WassemIsaac** [comment]
Why was this case closed ? @arturovt
