### ISSUE TITLE
Support --codeCoverage

### ISSUE THREAD

**Issue by bovandersteene** [just-jeb/angular-builders#247]
**Is your feature request related to a problem? Please describe.**
Today, the jenkins server is configured as following, to run tests:
`ng test {projectname}} --watch=false --code-coverage`
If I run my application with jest angular builders then it fails with: 
Unknown option: '--codeCoverage'

**Describe the solution you'd like**
It would be nice if the defaults are also supported in command line like codeCoverage. Maybe you can create an alias for it --coverage => --codeCoverage=true ?

**Additional context**
I cannot change the jenkins configuration if this would be the solution ;-)

**Comment by meltedspark** [comment]
I assume it was configured for Karma and now you're switching to Jest?  
The builder officially supports all the Jest options, among them `collectCoverage` and `collectCoverageFrom`. Since `codeCoverage` is not one of the Jest options it would be confusing to add such an alias. The builder should be aligned with Jest.  
Unfortunately the right solution here is to change Jenkins config indeed.  
Alternatively I could support a generic aliases configuration but since you're the only one who asked for this I prefer to invest in other issues.  
You're welcome to PR though for generic alias configuration.

**Comment by unstephenk** [comment]
I can't get code coverage to work with Karma either. Does anyone have a working example?
