### ISSUE TITLE
Jest builder - unable to configure external scripts

### ISSUE THREAD

**Issue by zshlomyz** [just-jeb/angular-builders#643]
Hi,
I migrate my Angular application from Karma to Jest.
At the Angular.json file, the @angular-devkit/build-angular:karma contain a scripts attribute that configure the external scripts that needed for executing the tests.
I can't find a way to set this attribute using the @angular-builders/jest:run builder.
It has to be configured at the jest.config file? how? there is no import attribute there also.
Thanks,
Shlomi

**Comment by just-jeb** [comment]
Hi Shlomi.
Indeed there is no such an option in the builder because you have all the tools provided by Jest.  
In order to load global scripts into your test context you should use [setupFilesAfterEnv](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) option in Jest config.  
Just create a file where you import these global scripts and add it to the `setupFilesAfterEnv` array in your config.  

Please let me know if it helped you.

**Comment by zshlomyz** [comment]
Thanks @just-jeb ! It works!
