### ISSUE TITLE
replace files programmatically

### ISSUE THREAD

**Issue by BioPhoton** [just-jeb/angular-builders#645]
First thanks for your work!
It saved me a lot of time and headaches!

I use your custom webpack builder for a project.

I was able to edit angulars entry files.

A problem that I'm struggling with ATM is changing file replacements programmatically.

A basic example is an environment file.
In angular.json:
```json
"fileReplacements": [
  { 
    "replace": "projects/demo/src/environments/environment.ts", "with": 
    "projects/demo/src/environments/environment.prod.ts" 
  }
 ]
```

I tried changing the options but is not showing the changes in the build.
Only changes in the angular.json file work

A pointer to the right place in your codebase would be very helpful!

Thanks for your time!

**Comment by just-jeb** [comment]
I guess you need it because it you're generating the pass based on conditions? If the conditions are static you may just consider using different configuration and run your build with `--configuration` flag.  
Otherwise you'll have to modify `AngularCompilerPlugin` configuration, since [this is where](https://github.com/angular/angular-cli/blob/2b22e73990a9250be963cbd84b513b0ce7fe2bef/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L30) they use the `fileReplacements` options.
