### ISSUE TITLE
watch is false from 11.x.x

### ISSUE THREAD

**Issue by skoropadas** [just-jeb/angular-builders#986]
## Describe the Bug

After update `@angular-builders/custom-webpack` to 11.x.x `WebpackCompiler.options.watch` starts to be `false`, when you run server by `ng s` command.

## Minimal Reproduction

- Make webpack plugin.
- Run `ng s`
- See `WebpackCompiler.options.watch`

## Expected Behavior

WebpackCompiler.options.watch must be true, it can be false only if you run `ng build`

## Environment

<pre><code>
Libs
- @angular/core version: 11.2.0
- @angular-devkit/build-angular version: 0.1102.0
- @angular-builders/custom-webpack version: 11.1.1

For Tooling issues:
- Node version: 12.22.1
- Platform:  Linux, Windows
</code></pre>

**Comment by just-jeb** [comment]
The builder does not change any Webpack option, it takes what Angular CLI provides and adds your config on top of it.   
When you're saying "WebpackCompiler.options.watch must be true", on what are you basing this? Do you know for sure that Angular 11 set it to `true` (and therefore the builder is changing it to `false`)?

**Comment by skoropadas** [comment]
Then it seems to be an Angular CLI problem.
And of course I don't know for sure that Angular 11 set it to true, I'm just waiting for the webpack environment to conform to the webpack documentation.

**Comment by just-jeb** [comment]
Well, custom webpack config is not supported officially by Angular CLI, it is only available through third party builders like this one.  
In fact, they do so in order to provide an abstraction layer on top of Webpack so that they would be able to easily switch to another build chain if they want. 
Internal implementation details (which Webpack is considered to be) are completely user's responsibility from their perspective and they can change it/the usage of it anytime. 
The only thing that they are supposed to keep backward compatible/well documented is their public API surface (`angular.json` etc.).

**Comment by skoropadas** [comment]
Thanks for your reply, very informative! So I close the issue, thanks again

**Comment by guilhermetod** [comment]
Just for reference, I ran into this issue and it's really an [Angular 11 thing](/angular/angular-cli/commit/1c61ced55cf59519f90ccb506f7fe811d56fe740)
